-- CREATE TABLE MATH_STATS_DATA (
--     ID NUMBER,
--     ANGLE_DEG NUMBER,
--     ANGLE_RAD NUMBER,
--     NUM1 NUMBER,
--     NUM2 NUMBER,
--     NUM3 NUMBER,
--     SALES NUMBER,
--     SALES_PREV NUMBER
-- );

-- INSERT INTO MATH_STATS_DATA VALUES (1, 30, 0.5236, 2, 4, 6, 1200, 1000);
-- INSERT INTO MATH_STATS_DATA VALUES (2, 45, 0.7854, 5, 3, 9, 1500, 1400);
-- INSERT INTO MATH_STATS_DATA VALUES (3, 60, 1.0472, 7, 8, 2, 1800, 1600);
-- INSERT INTO MATH_STATS_DATA VALUES (4, 90, 1.5708, 6, 1, 5, 2100, 2000);
-- INSERT INTO MATH_STATS_DATA VALUES (5, 120, 2.0944, 9, 7, 4, 2400, 2300);

-- Select * from MATH_STATS_DATA

-- Find sine value of an angle.
-- SELECT ANGLE_DEG, SIN(ANGLE_RAD) AS SINE_VAL FROM MATH_STATS_DATA;

-- Find cosine value of an angle.
-- SELECT ANGLE_DEG, COS(ANGLE_RAD) AS COS_VAL FROM MATH_STATS_DATA;

-- Find tangent value.
-- SELECT ANGLE_DEG, TAN(ANGLE_RAD) AS TAN_VAL FROM MATH_STATS_DATA;

-- Convert degrees to radians.
-- SELECT ANGLE_DEG,ANGLE_DEG * (3.14159265358979 / 180) AS RADIAN_VAL FROM MATH_STATS_DATA;

-- Convert radians to degrees.
-- SELECT ANGLE_RAD,ANGLE_RAD *(180/3.14159265358979) AS DEGREE_VAL FROM MATH_STATS_DATA;

-- Find logarithm (base 10) of a number.
-- SELECT NUM1, LOG(10, NUM1) AS LOG_BASE10 FROM MATH_STATS_DATA;

-- Find natural log of a number.
-- SELECT NUM1, LN(NUM1) AS NATURAL_LOG FROM MATH_STATS_DATA;

-- Find square of a number.
-- SELECT NUM1, POWER(NUM1,2) AS SQUARE_VAL FROM MATH_STATS_DATA;

-- Find cube of a number.
-- SELECT NUM1, POWER(NUM1,3) AS CUBE_VAL FROM MATH_STATS_DATA;

-- Calculate factorial of a number.

-- Find greatest value among three numbers.
-- SELECT NUM1, NUM2, NUM3,GREATEST(NUM1,NUM2,NUM3) AS MAX_VAL FROM MATH_STATS_DATA;

-- Find least value among three numbers.
-- SELECT NUM1, NUM2, NUM3, LEAST(NUM1,NUM2,NUM3) AS MIN_VAL FROM MATH_STATS_DATA;

-- Calculate variance of sales.
-- SELECT VARIANCE(SALES) AS SALES_VARIANCE FROM MATH_STATS_DATA;

-- Calculate standard deviation of sales.
-- SELECT STDDEV(SALES) AS SALES_STDDEV FROM MATH_STATS_DATA;

-- Find average deviation.
-- SELECT AVG(ABS(SALES - (SELECT AVG(SALES) FROM MATH_STATS_DATA))) AS AVG_DEVIATION FROM MATH_STATS_DATA;

-- Calculate geometric mean.
-- SELECT EXP(AVG(LN(SALES))) AS GEOMETRIC_MEAN FROM MATH_STATS_DATA;

-- Calculate harmonic mean.
-- SELECT COUNT(*) / SUM(1/SALES) AS HARMONIC_MEAN FROM MATH_STATS_DATA;

-- Find sum of squares.
-- SELECT SUM(POWER(SALES,2)) AS SUM_OF_SQUARES FROM MATH_STATS_DATA;

-- Calculate correlation between two columns.
-- SELECT CORR(SALES, SALES_PREV) AS CORRELATION FROM MATH_STATS_DATA;

-- Calculate regression slope.
-- SELECT REGR_SLOPE(SALES, SALES_PREV) AS REGRESSION_SLOPE FROM MATH_STATS_DATA;